USE localidades;

select * from cidade;
select * from estado;

# 1
-- FAÇA UMA JUNÇÃO DA TABELA CIDADE E ESTADO MOSTRANDO:
-- NOME DA CIDADE, SIGLA DO ESTADO. APENAS NAS CIDADES QUE TEM ESTADO

SELECT cidade.Nome, estado.Sigla
FROM CIDADE
INNER JOIN ESTADO ON cidade.Estado_ID = estado.id;

# 2
-- FAÇA UMA JUNÇÃO DA TABELA CIDADE E ESTADO, MOSTRANDO:
-- NOME DA CIDADE, SIGLA DO ESTADO. TODAS AS CIDADES, INDEPENDENTE DE TEREM ESTADO

SELECT cidade.Nome, estado.Sigla
FROM CIDADE 
LEFT JOIN ESTADO ON CIDADE.ESTADO_ID = CIDADE.ID;
 
# 3
-- FAÇA UMA JUNÇÃO DA TABELA CIDADE E ESTADO, MOSTRANDO:
-- NOME DA CIDADE, SIGLA DO ESTADO. MOSTRE TODOS OS ESTADOS, INDEPENDENTE DE TEREM CIDADES
 
SELECT cidade.Nome, estado.Sigla
FROM CIDADE 
LEFT JOIN ESTADO ON CIDADE.ESTADO_ID = ESTADO.ID;
 
# 4
-- FAÇA UMA JUNÇÃO DA TABELA CIDADE, ESTADO E PREFEITO:
-- CIDADE.NOME, ESTADO.SIGLA/UF, PREFEITO.NOME, PREFEITO.DATAPOSSE
-- PARA TODAS AS CIDADES QUE TEM PREFEITO

SELECT cidade.Nome, estado.Sigla, prefeito.nome, prefeito.dataposse
FROM CIDADE 
LEFT JOIN ESTADO ON CIDADE.ESTADO_ID = ESTADO.ID
RIGHT JOIN PREFEITO ON CIDADE.PREFEITO_ID = PREFEITO.ID;

